### ISSUE TITLE
✅ Agent Status Monitoring

### ISSUE THREAD

**Issue by gluax** [monadicus/snarkops#206]
## ✅ Task

We need a better way to monitor agents within an env.

Keeping track of information such as:
- [x] agent version
- [x] agent node height
- [x] agent node status
- [x] agent download progress
  - [x] ledger/checkpoint
  - [x] node binary

## Motivation

Allows for us to:
- select agents by latest height for operations
- better monitor the status of agents and see why they stopped
- possibly be able to swap node modes without closing the ledger

## Details

effects:
- AOT
- Control Plane
- Agent

Related to #141
