### ISSUE TITLE
✅ Get CLI Commands

### ISSUE THREAD

**Issue by gluax** [monadicus/snarkops#208]
## ✅ Task

- [x] `scli env get mapping delegated account.0`
- [x] `scli env get tx <id>`
- [x] `scli env get height`
- [x] `scli env agent status`

## Motivation

The ability to fetch data from Aleo for an env, from the freshest available agent.

## Details

Effects:
- scli

Blocked by #206.
